name: 'Google Play Developer get latest Version Code'
description: 'This gets the latest version code of the latest bundle uploaded to Google Play.'
author: 'Luís Duarte (LuisDuarte1)'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'play'
  color: 'blue'

# Define your inputs here.
inputs:
  google_service_account_json:
    description: 'The service account json content.'
    required: true
  package_name:
    description: 'Google Play package name of the app'
    required: true
  track:
    description: 'Track to get the latest version string from'
    required: false

# Define your outputs here.
outputs:
  latest_version_code:
    description: 'Latest version_code'
  latest_version_name:
    description: 'Latest version name of a specific track. In order to work you must provide the track as an input'
runs:
  using: node20
  main: dist/index.js
