name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Action
        id: test-action
        uses: ./
        with:
          google_service_account_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          package_name: "pt.up.fe.ni.uni"


      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.latest_version_code }}"
